version: "3"

services:
  my-db:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - counter-net
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb-data:/data/db

  my-mongo-ui:
    image: mongo-express
    ports:
      - 8081:8081
    networks:
      - counter-net
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=my-db
    depends_on:
      - my-db
    restart: always

  counter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - counter-net
    depends_on:
      - my-db

networks:
  counter-net:

volumes:
  mongodb-data:
